# -*- coding: utf-8 -*-
"""Face detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eBbYy7J4cA7IFZ8KqowT1cz86PiKTY6c

# Title: Face Recognition System
"""

print("Face Detection System")

"""## Installing libraries"""

! sudo apt install cmake

pip install face_recognition

import cv2
import face_recognition
from google.colab.patches import cv2_imshow

"""Upload and unzip images **folder**"""

!unzip "/content/FR images.zip"

"""## Print any Image"""

srkImage = face_recognition.load_image_file("/content/FR images/srk1.jpg")
srkImage = cv2.cvtColor(srkImage, cv2.COLOR_BGR2RGB)
cv2_imshow(srkImage)

"""# FR CODE HERE..."""

faceArray = face_recognition.face_locations(srkImage)[0] #[0] for delocating an array
print(faceArray)


# #draw a rectangle on face
#             Image             arrayTuple1,                 arrayTuple2,            green color(RGB,A)
cv2.rectangle(srkImage, (faceArray[3], faceArray[0]), (faceArray[1], faceArray[2]), (30, 225, 0),5)
cv2_imshow(srkImage)

faceEncoding = face_recognition.face_encodings(srkImage)[0] #[0] for delocating an array
# faceEncoding

"""# Testing an Image

Read Image for testing
"""

testImage1 = face_recognition.load_image_file("/content/FR images/srk2.jpg")               
testImage1 = cv2.cvtColor(testImage1, cv2.COLOR_BGR2RGB)
cv2_imshow(testImage1)

"""encode testing **image**"""

faceArray = face_recognition.face_locations(testImage1)[0] #[0] for delocating an array
# print(faceArray)
# #draw a rectangle on face
#             Image             arrayTuple1,                 arrayTuple2,            green color(RGB,A)
cv2.rectangle(testImage1, (faceArray[3], faceArray[0]), (faceArray[1], faceArray[2]), (30, 225, 0),5)
cv2_imshow(testImage1)

testEncoding = face_recognition.face_encodings(testImage1)[0] #[0] for delocating an array
# faceEncoding
result = face_recognition.compare_faces([faceEncoding], testEncoding)[0]
print(result)

"""# Test Images Using Loop"""

images = ['/content/FR images/srk1.jpg', '/content/FR images/srk2.jpg', '/content/FR images/srk3.jpg', '/content/FR images/sk1.jpg', '/content/FR images/sk2.jpg']
for image in images:
  print(image)
  img = face_recognition.load_image_file(image)
  img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
  imgArray = face_recognition.face_locations(img)[0]
  cv2.rectangle(img, (imgArray[3], imgArray[0]), (imgArray[1], imgArray[2]), (30, 225, 0),5)
  imgEncoding = face_recognition.face_encodings(img)[0]
  results = face_recognition.compare_faces([faceEncoding], imgEncoding)[0]
  print(results)
  cv2_imshow(img)